# -*- coding: utf-8 -*-
"""AlgorithmStudy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bImmuZuQjbZjLkuZ6BvwoZDqtyNAbekE

### **DAY 1**

**Q1:** In this example we will try to make a small payroll. In other words, when the day worked and daily wages are entered on the keyboard, we will make the algorithm that calculates the net monthly wage to be received by that person according to the following rules .

Monthly gross income = daily wage * number of days worked
Income tax = monthly gross income * tax rate
Net monthly wage = Monthly gross income - Income tax

Rules:
* The number of working days should not be more than 31
* The income tax rate should be applied as 20% of the monthly gross income. However, it should be applied as 25% for those with a monthly income of more than 5000.
"""

def salary(working_day, daily_price):
  if working_day < 31:
    monthly_income = working_day * daily_price
    if monthly_income > 5000:
      tax_rate = monthly_income / 4
    else:
      tax_rate = monthly_income / 5 
    income_rate = monthly_income * tax_rate
    net_monthly_fee = monthly_income - income_rate
    return net_monthly_fee
  else:
    working_day = working_day -31
    return salary(working_day, daily_price)
salary(30,50)

"""**Q2**"""

def math(mid1, mid2, final, project):
  score = mid1*0.1+ mid2*0.1+ final*0.6+ project*0.2
  if 0<mid1<100 and 0<mid2<100 and 0<final<100 and 0<project<100:
    if score <=100 and score >85:
      return "A"
    elif score <=85 and score >70:
      return "B"
    elif score <=70 and score >55: 
      return "C"
    elif score <=55 and score >45:
      return "D"
    elif score <=45 and score >25:
      return "E"
    elif score <=25 and score >0:
      return "F"
def physic(mid1, mid2, final, project):
  score = mid1*0.1+ mid2*0.1+ final*0.6+ project*0.2
  if 0<mid1<100 and 0<mid2<100 and 0<final<100 and 0<project<100:
    if score <=100 and score >85:
      return "A"
    elif score <=85 and score >70:
      return "B"
    elif score <=70 and score >55: 
      return "C"
    elif score <=55 and score >45:
      return "D"
    elif score <=45 and score >25:
      return "E"
    elif score <=25 and score >0:
      return "F"
lesson1 = math(100,32,55,11) 
lesson2 = physic(98,76,85,92)
print("Letter grade in Math: {}".format(lesson1))
print("Letter grade in Physic: {}".format(lesson2))

"""**Q3:** The algorithm of the program that takes the factorial of an entered number ."""

number = int(input("Enter a number: "))
fac = 1

if number < 0:
  print("The factorial of negative numbers cannot be calculated.")
elif number == 0:
  print("0!=1")
else:
  for i in range(1, number+1):
    fac = fac * i
  print(number," factorial of the number", fac)