# -*- coding: utf-8 -*-
"""sumnumber.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MV_DMQj7UwBUxEfNwDbY4PLMD6m7y0DY

Program that adds 10 numbers entered on the keyboard
"""

rlist = []
for i in range(0,10):
  rlist.append(int(input()))
toplam = 0
for i in rlist:
  toplam = toplam + i
print(toplam)