# -*- coding: utf-8 -*-
"""06_largestnumber.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MV_DMQj7UwBUxEfNwDbY4PLMD6m7y0DY

The program that finds the largest of the 10 numbers entered on the keyboard
"""

rlist = []
for i in range(0,10):
  rlist.append(int(input()))
largest = 0
for num in rlist:
  if num > largest:
    largest = num
  
print("Largest", largest)